import Link from "next/link";
import Image from "next/image";
import "./globals.css";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Skeletor Dapps</title>
      </head>
      <body className={`bg-[#151515] ${inter.className}`}>
        <div className="flex flex-col justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
